### ISSUE TITLE
Crash after update + feature request

### ISSUE THREAD

**Issue by ghost** [EmmaTellblom/Mensinator#135]
Hi,
Thank you for this amazing app.

Bug:
I just updated to the new release v1. 9 and the app crashes. I tried to open it after update, it crashed immediately. I cleared cache, didn't help. Furthermore, I cleared all the data, I was able to open the app, but it crashed after trying to add data into it.

Feature request:
The way you have made the symptoms, it would be great if there would be a similar set-up for treatments. At the moment, I have added all my treatments under symptoms, but it would be nice if they could be two different categories.
It would also be nice if there was a summary of the symptoms underneath the calendar, so you would be able to see information at a glance.

**Comment by EmmaTellblom** [comment]
Hi! 
Sorry for the app crashing, I think I know what is the issue and I have just re-written that part of the app. (It has to do with predictions). I will look it over once more but hopefully it will be fixed with the next update. 

(now I realize that we talked about this on Discord, lol). Yes this is a feature that we will be implementing in the future!

**Comment by EmmaTellblom** [comment]
Im closing this since I already have an issue for treatments and I think crashes will go away after next update. If you want to try next version already, reach out to me on Discord and I can give you the APK.
