### ISSUE TITLE
Add Italian language

### ISSUE THREAD

**Issue by serrq** [EmmaTellblom/Mensinator#190]

**Comment by EmmaTellblom** [comment]
Hi @serrq
This would be awesome! Are you able to translate to Italian? We could help you if you getting started if you are. Else we need to get in touch with someone who can translate and I don't have any contacts right now so I can't give you a time line on when this could be implemented.

**Comment by EmmaTellblom** [comment]
@serrq This is the english file that needs to be translated into italian. If you translate what you know and ask about the stuff that is unclear we can get it into the app!
https://github.com/EmmaTellblom/Mensinator/blob/main/app/src/main/res/values/strings.xml

**Comment by EmmaTellblom** [comment]
@serrq You could edit it in a texteditor as an xml-file basiclly is a textfile. It would be fine if you did it here in raw text too, but it might be a bit long and weird? (Not sure if Github has restrictions on comment length). 
But what you do is that you translate the words between the XML-tags, like this;

<resources>

    
    <string name="app_name">Mensinator</string>

    
    <string name="previous">Precedente</string>
    <string name="next">Successivo</string>
    <string name="period_button">Periodo</string>
    <string name="symptoms_button">Sintomi</string>
    <string name="ovulation_button">Ovulazione</string>
    <string name="period_button_selected">Rimuovi Periodo</string>
    <string name="period_button_not_selected">Aggiungi Periodo</string>
    <string name="ovulation_button_selected">Rimuovi Ovulazione</string>
    <string name="ovulation_button_not_selected">Aggiungi Ovulazione</string>


</resources>

The best would be if you forked the repo, made the changes and then created a pull request. That way you would be automatically listed as a contributor in our main repo. But if that's not important then you can just translate the link I sent you yesterday and give it to us and we can import it into the app.

**Comment by EmmaTellblom** [comment]
@serrq You can follow this guide;
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo

**Comment by EmmaTellblom** [comment]
@serrq Great! If you want we can import it as is, or do you still want to make a fork and a pull request?

**Comment by carstenhag** [comment]
Thanks a lot!!! 🚀 😄 🥇 
I have integrated the translations and appplied some minor fixes so that the app can be built & that the translations are similar to the other languages.

I built the app with the translations in them for you to try (can't upload .apk files here, so I had to zip it). If you don't want to do this, I also uploaded a video:


https://github.com/user-attachments/assets/404620ab-992c-4efc-a4db-20642912a519



[mensinator-add-italian.zip](https://github.com/user-attachments/files/17908790/mensinator-add-italian.zip)

**Comment by EmmaTellblom** [comment]
@serrq That might be bad choices of names, lol. But the first one is that the predicted date for your next period has passed. So basically the app has predicted a period for the passed due to too little data. Does it make sense? And the other one is that the app has predicted a period for the future.

**Comment by EmmaTellblom** [comment]
And regarding luteal and follicular phase, we actually use follicular phase in the code when we calculate the ovulation date. But we don't write it anywhere. And we only write luteal phase in the settings (and faq) because it's a different way of calculating period that the user can calculate. Otherwise it would just be in the calculations code too.

**Comment by EmmaTellblom** [comment]
@serrq
I doubled check and I now understand why you are confused! A while back I had different texts of the predicted date had passed, but then I found that this was obvious so I changed the texts so it's the same. I should clean this up so it's only one text for this in the files... I'm sorry for the confusion, I had forgotten that I had changed it to be the same..
