### ISSUE TITLE
Set autobackup to false

### ISSUE THREAD

**Issue by EmmaTellblom** [EmmaTellblom/Mensinator#57]
Just saw that autobackup is set to true in the android manifest. This should be set to disabled since we do not want Google to backup data from the app due to privacy reasons.

**Comment by FrenchGithubUser** [comment]
Hi, I'm trying to backup the app using seedvault and it says that the app doesn't allow for backup.

It seems like the autobackup entry in the manifest is the reason why. Also mentionned here : https://github.com/seedvault-app/seedvault/issues/81#issuecomment-604837572

I understand that backing up this data with google services isn't ideal, but : 

- what about users who want to back it up with a privacy-respecting solution like seedvault ?
- users who have a google-based solution to backup their data is often (if not always) acting at system-level, and google already has access to this data, whether the autobackup is true or false.

**Comment by EmmaTellblom** [comment]
@FrenchGithubUser Hi! There is a backup (called export and exports in json format) feature in the settings of the app. Since one of the main goals/features of the app is privacy we don't want to let Google backup the data. It's all in the hands of the user.

**Comment by FrenchGithubUser** [comment]
Yes I get it. But this doesn't allow for automation, that's why tools like seedvault exist (https://github.com/seedvault-app/seedvault). Seedvault can backup app data to different places, including self-hosted cloud solutions or local stoarage, regularly and programmatically. Also, the produced backup is encrypted by seedvault itself.

Most apps with sensitive data (lke TOTP apps for example) allow for backup through seedvault for obvious reasons. So again, I understand the concerns with google having access to the data, but they already have access to it due to system-level integration anyways.

Breaking your phone, losing it, etc, means loosing all the data from Mensinator since the last manual backup. And most people won't do manual backups because they rely on automated solutions like seedvault.

Please let me know if something is not clear :)

**Comment by carstenhag** [comment]
I guess this makes sense to have. Quote from the seedvault [FAQ](https://github.com/seedvault-app/seedvault/wiki/FAQ):

> Instead of opting out completely, app developers can say that their app [should only get backed up, if the backup is encrypted](https://developer.android.com/guide/topics/data/autobackup#define-device-conditions).

I'm not entirely sure if we should do it though. It takes time to develop & to maintain this, as it has to be regularly tested. Having a non-functioning automatic backup is not good. In any case, please submit a new feature request for this if you want it :)

**Comment by FrenchGithubUser** [comment]
you could simply allow backup in the android manifest, that's quick. then seedvault backs up the data folder, which should be easily restorable, not sure how much testing this really requires. I will submit a feature request
