### ISSUE TITLE
Screen protection over "recent apps" and "screenshot"

### ISSUE THREAD

**Issue by serrq** [EmmaTellblom/Mensinator#69]
Some apps give the ability (optional) to switch ON/OFF the "screenshot" and "recent apps" protection feature by other prying apps.
Basically a privacy feature. Here an implementation and some examples.

![271815693-2e7d379a-c81c-41b1-88d2-7170fc429af7](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/8177e581-55ce-4aab-b2ed-41fb7fc3c1d8)

![1000042037](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/de821f85-2361-437f-95be-fc2a4783ff54)

![1000042036](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/499a76af-6db7-4f6b-b886-f06ff7dad708)

**Comment by EmmaTellblom** [comment]
Great idea! I'll add it to our backlog.

**Comment by rubens23** [comment]
This should be pretty easy to implement. I'll do it and send a pull request for you guys to approve

**Comment by EmmaTellblom** [comment]
@rubens23 That would be very helpful! I think we should add this as a setting, because sometimes you might want to send screenshots. (at least I would want to do that, lol).
So we would need a new setting in the database (don't forget onCreate and on Upgrade) and also some new code in settingsdialog.kt.
Let me know if you have any questions! 
Let me know if you need any help!

**Comment by rubens23** [comment]
ah I see. I'll take a look at the database structure and think on how to implement this feature as setting so the user can turn on and off if he wants

**Comment by EmmaTellblom** [comment]
This has been fixed in commit [4d18f97] ! Will be released in upcoming version,
