### ISSUE TITLE
Please removing unnecessary permissions

### ISSUE THREAD

**Issue by serrq** [EmmaTellblom/Mensinator#70]
Privacy enhancement.

![1000117846](https://github.com/user-attachments/assets/7c0a4be4-e282-40df-9eaa-60b42afc3307)

-----------------

![1000117849](https://github.com/user-attachments/assets/8d015b5b-0332-435e-b14e-2bf4c54c0228)

**Comment by EmmaTellblom** [comment]
I have investigated this and its because of the library libs.androidx.work.runtime.ktx (work-runtime-2.9.0). We do not use network discovery, but it is default in the library because it can be used to schedule requests being sent when user has network. We only use it to schedule notifications to the phone which do not require network discovery. 
But I get your point. I will add this as a new feature request to see if we can rebuild this functionality using another library or such that does not require this.

**Comment by carstenhag** [comment]
Just saw this. FYI @EmmaTellblom, you can force-remove permissions from the app (which were added by some library). https://stackoverflow.com/a/33105591/3991578
